### ISSUE TITLE
Get DHCP Working again

### ISSUE THREAD

**Issue by grndlvl** [GollyGood/dstack#47]
At first it seemed like it was only because the GustAdditions were not being loaded. But, even after creating a custom init upstart script it still asn't the issue. 

We already have the proselytized solution where you create a symlink to /user/lib/VBoxAdditions from the /opt/VBox...

We also attempted running vboxadd setup directly. And attempted to install virtualbox-guest-dkms package without any luck.

The errors vary:
1) Sometimes fails on reloads & halt+up during SSH due to timeout
2) Sometimes fails on mounting the share directories on reload & halt+up
3) Sometimes throws error about not being able to retrieve the IPAddress from the guest machine on reload & halt+up.

https://github.com/mitchellh/vagrant/issues/3341

**Comment by grndlvl** [comment]
This appears to be causing issues on reload... maybe we need a better title.

**Comment by kpolymorphic** [comment]
after new box (0.1.1) cannot reproduce reliably. Test system: debian 8 (jessie) with virtualBox 4.3.18 and vagrant 1.6.5. The only time I could reproduce was triggering simultaneous vagrant reloads on multiple boxes (probably triggers port collision or dhcp server timeouts).

**Comment by grndlvl** [comment]
After messing with this some more I was finally able to get this to work using vagrant-vbguest with virtualbox 4.3.20. Closing.
